### ISSUE TITLE
if more than 1 replicate spectrum, which one used to query main database?

### ISSUE THREAD

**Issue by ggonzalezp** [brain-research/deep-molecular-massspec#17]
if there's more than 1 replicate spectrum for a given compound in the replicates database, which one do you use to query the main database? a randomly-selected one? or do you query with all of them and average performance? 

Additionally, if training with a different dataset that has a few spectra for a given compound, should I include them all in the replicates sdf file or only one?
Thanks!

**Comment by jnwei** [comment]
Thanks for the interest!

We reported our results based on the spectra; we didn't aggregate the results for a single molecule if it had multiple replicates spectra.

I'm not sure if I fully understand your second question. We use the replicates file for evaluation only, so having multiple spectra for a single model doesn't affect the model's performance. For training purposes, it would probably be fine to include multiple spectra for the same molecule.

**Comment by ggonzalezp** [comment]
thanks for your response!
To elaborate on my second question:
I want to train and evaluate the model with a different dataset. In this dataset, the replicates library contains sometimes several spectra for the same molecule. What should I do in these cases (what did you do in these cases if you had cases like this?)? Should I include all different spectra for a single molecule or include just a randomly-selected one? If I include several spectra for a single molecule, which one is used to query the augmented library during evaluation?

**Comment by jnwei** [comment]
For our project, our goal was to show how often we could recover the right molecule identity in the top K hits. We regarded multiple spectra for a single molecule in the replicates library as independent queries, and reported the results over all spectra (rather than over all molecules).

If you'd like to report your results based on recovery by molecule, maybe it makes more sense to randomly select a spectra, as you suggested. If the spectra aren't super noisy and different, you could run each spectra as a query, and then find a way of aggregating the results, perhaps by overlap.

**Comment by ggonzalezp** [comment]
thank you!
